apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
       env: slave
  template:
    metadata:
     name: myweb-pod
     labels:
       env: slave
    spec:
      containers:
      - name: myweb-con
        image: hardik1999/jenkins_slave
